### ISSUE TITLE
'point_cloud' in ddad dataset not found.

### ISSUE THREAD

**Issue by synsin0** [GANWANSHUI/GaussianOcc#12]
Hello, I attempt to reproduce training and test on DDAD dataset and faces multiple errors. I'd like to ask about the 'point_cloud' in ddad dataset. First, the point_cloud in DDAD.tar are in .npz file but not .npy file, Then, the camera timestamp index_temporal does not match file name of point cloud. Last, the point_cloud seems not used later. Should I just neglect the point cloud file?

**Comment by synsin0** [comment]
I eval the DDAD dataset with official checkpoint and gets the log 
[ddad_log.txt](https://github.com/user-attachments/files/16795328/ddad_log.txt). Is it normal for depth prediction?

**Comment by GANWANSHUI** [comment]
> I eval the DDAD dataset with official checkpoint and gets the log [ddad_log.txt](https://github.com/user-attachments/files/16795328/ddad_log.txt). Is it normal for depth prediction?

Yes, it is normal though a little worse than my test, you can do some 3d occ visualization.

**Comment by GANWANSHUI** [comment]
> Hello, I attempt to reproduce training and test on DDAD dataset and faces multiple errors. I'd like to ask about the 'point_cloud' in ddad dataset. First, the point_cloud in DDAD.tar are in .npz file but not .npy file, Then, the camera timestamp index_temporal does not match file name of point cloud. Last, the point_cloud seems not used later. Should I just neglect the point cloud file?

Yes, you can neglect the unused files.
