### ISSUE TITLE
Where I can find and change the pose when splatting rendering at "Cross View Gaussian splatting" ?

### ISSUE THREAD

**Issue by RyanPham19092002** [GANWANSHUI/GaussianOcc#13]
Hi! Thanks for your great works.
Can you show me where you give the pose for Cross View Gaussian splatting block then rendering the view to compute loss ? 
I want to change a pose to see the rendering capabilities of this model.
Thanks for your help.

**Comment by GANWANSHUI** [comment]
I still did not release the code for stage 1, it may take some time to release.

**Comment by RyanPham19092002** [comment]
Thank you for your reply, I really hope you can notify when stage 1 is released, I'm looking forward to it.
