### ISSUE TITLE
The run.sh file is missing

### ISSUE THREAD

**Issue by SHEVIP** [GANWANSHUI/GaussianOcc#14]
Hi! Thank you very much for such advanced and great work.
When I try to reproduce the code, I get the following error: **[Errno 2] No such file or directory: 'run.sh'**
I didn't see this file in the project repository either, and I was wondering if I was missing something?

**Comment by GANWANSHUI** [comment]
ignore this [files](https://github.com/GANWANSHUI/GaussianOcc/blob/c139a9f8353bbc7bec510920d0a768a63611d88f/runner.py#L380) is OK

**Comment by SHEVIP** [comment]
Sorry,but when i run the "sh run_gs_occ.sh" The program does not run properly and an error is reported[Errno 2] No such file or directory: 'run.sh'
how can i fix it ,sincere appreciation

**Comment by GANWANSHUI** [comment]
replace the `run.sh` into `run_gs_occ.sh` in this [line](https://github.com/GANWANSHUI/GaussianOcc/blob/c139a9f8353bbc7bec510920d0a768a63611d88f/runner.py#L380)

**Comment by SHEVIP** [comment]
Thanks Thanks Thanks Thanks a lot!!!
