### ISSUE TITLE
missing export_gt_depth_ddad.py file

### ISSUE THREAD

**Issue by LevinJ** [GANWANSHUI/GaussianOcc#15]
In the project readme, we have instruction on how to export ddad depth maps for evaluation
```
cd tools
python export_gt_depth_ddad.py val
```

but there seems to be no export_gt_depth_ddad.py file in the tools folder.

**Comment by GANWANSHUI** [comment]
Hi, thank you. I will update it later, before that, please refer to [this](https://github.com/GANWANSHUI/SimpleOccupancy/blob/master/tools/export_gt_depth_ddad.py).
