### ISSUE TITLE
The versions of mmcv and mmdet

### ISSUE THREAD

**Issue by Hey-ChaoKe** [GANWANSHUI/GaussianOcc#17]
Following the current installation, I always find these two libraries missing and encounter compatibility issues when installing them myself. Could you let me know which versions of mmcv and mmdet were used in this work? Thanks!

**Comment by LevinJ** [comment]
just for your reference , i got the code running with below version combination

mmcv-full                            1.7.2              
mmdet                                2.28.2            
mmengine                             0.10.4
