### ISSUE TITLE
Why is scale negative？

### ISSUE THREAD

**Issue by HCaelrs** [GANWANSHUI/GaussianOcc#19]
Why is pc['get_scaling'] in prepare_gs_attribute is negative? [https://github.com/GANWANSHUI/GaussianOcc/blob/c139a9f8353bbc7bec510920d0a768a63611d88f/networks/occupancy_decoder.py#L547](url)

**Comment by GANWANSHUI** [comment]
This is personal definition. It should be OK to set is positive, you can have a try on it.
