### ISSUE TITLE
About Pose Free

### ISSUE THREAD

**Issue by Kamp-Sun** [GANWANSHUI/GaussianOcc#2]
Excellent work! May I ask, if the system is pose-free, how do you use camera poses during the LSS projection or when interpolating to obtain BEV features?

**Comment by GANWANSHUI** [comment]
The pose free is saying the temporal pose in sequence, while we still require the surrounding 6D camera pose (the extrinsic) to provide the scale information from the overlap region as well as the lifting operation (2d to 3d).
