### ISSUE TITLE
Error issue for semantic loss

### ISSUE THREAD

**Issue by RONGSHENG0404** [GANWANSHUI/GaussianOcc#23]
Thanks for your open source work! I am tring to run your code and found an error when count semantic loss in file runner.py line 1225:
" semantic_loss += self.sem_criterion(pred_semantic.view(-1, self.opt.semantic_classes), target_semantic.view(-1).long()) "
Here, size of pred_semantic is [6, 180, 320, 3] but size of target_semantic is [6, 180, 320], which causes an error of 
"ValueError: Expected input batch_size (57600) to match target batch_size (345600)." 
I hope you can fix it.
Best regarding.

**Comment by GANWANSHUI** [comment]
Hi, I did not find such kind of error in my side, could you have a double check for the reason? thank you!

**Comment by RONGSHENG0404** [comment]
Thank you for your reply. I didn't state the question clearly before. 
This error is caused by the fact that the function “self.sem_criterion” is initialized with weights for 18 classes, but the predicted value “pred_semantic” does not have 18 classes, but only 3, which might come from RGB 3 channels. The forced conversion “view” change the of size of “pred_semantic” to (57600, 18). However, the size of label value "target_semantic" is (345600,1), which is a mismatch.
Maybe there is something wrong with my understanding. I am looking forward to your reply.
Best regards.

> Hi, I did not find such kind of error in my side, could you have a double check for the reason? thank you!

**Comment by GANWANSHUI** [comment]
You may have modified some configures. You can add my Wechat: 15521072307 if you have not solved this problem.

**Comment by johnren-code** [comment]
Hello, have you solved it?

**Comment by johnren-code** [comment]
I have the same question, how to solved it?

**Comment by GANWANSHUI** [comment]
The code is a precompiled submodule. You need to run rm -r build to delete the build directory, then recompile it by running python setup.py install before it can be used.

**Comment by johnren-code** [comment]
> The code is a precompiled submodule. You need to run rm -r build to delete the build directory, then recompile it by running python setup.py install before it can be used.

This answer is helpful. We should delete the `build` directory in the `submodule` directory, and recompile it.
