### ISSUE TITLE
Error for download 'semantic_labels'

### ISSUE THREAD

**Issue by Minghui-Hou** [GANWANSHUI/GaussianOcc#24]
<img width="864" alt="截屏2024-10-02 13 06 22" src="https://github.com/user-attachments/assets/8e9448a3-17b2-4d96-8277-f1613731c4a1">
Thanks for your great work! The download link for ‘semantic_labels’ is inaccessible. Could you please fix it? Thank you.

**Comment by GANWANSHUI** [comment]
The OccNeRF author removed the label and it was a bit large data to upload my downloaded data from my side. You may try to construct the label following [this](https://github.com/JunchengYan/GroundedSAM_OccNeRF/tree/fe556473e857db2339b57a4ddc801dc76871e0c6).

**Comment by GANWANSHUI** [comment]
New link is available: https://cloud.tsinghua.edu.cn/d/564c9ac19b5f4b54a774/
