### ISSUE TITLE
Unreasonable optimization results while `use_semantic=False`

### ISSUE THREAD

**Issue by eliliu2233** [GANWANSHUI/GaussianOcc#25]
Thanks for your great work! I have tried to run the training code with `use_semantic=False` in a subset of the training scenes on nuscenes, but failed to get a reasonable result. Have you tried this setting? Or is there any other setting I've ignored that needs to be modified? Looking forward to your reply. 
The figure below is the result with `use_semantic=True` and `contracted_coord = False`.
![0-250](https://github.com/user-attachments/assets/a9e8cbad-2a47-4804-aaf1-b6a66cbc7b32)
The figure below is the result with `use_semantic=False` and `contracted_coord = False`.
![0-2502](https://github.com/user-attachments/assets/aff09dea-2108-4251-bc37-2a57bb8ce582)

**Comment by GANWANSHUI** [comment]
Hi, How about the size of the subset? you may consider setting `weight_entropy_last , weight_distortion` with 0

**Comment by eliliu2233** [comment]
> Hi, How about the size of the subset? you may consider setting `weight_entropy_last , weight_distortion` with 0

I select 150 scenes in the training set to conduct the small experiment. I have tried to set `weight_entropy_last` and `weight_distortion` to 0, and get reasonable visualization results. Thanks for your useful suggestions!
![0-250](https://github.com/user-attachments/assets/1d4937ee-f8cf-42d3-93ed-808c930f4a26)
The settings of these two hyperparameters seem to be sensitive to the optimization process. And there is an interesting phenomenon that the 2D semantic supervision seems to have significant impact on geometry of GaussianOcc, while it was not found in OccNeRF using volume rendering.

**Comment by GANWANSHUI** [comment]
Yes, we also observe that phenomenon which is great.
