### ISSUE TITLE
adapt to other dataset, such as kitti360 with a single view camera input

### ISSUE THREAD

**Issue by lingbo-yu** [GANWANSHUI/GaussianOcc#26]
hi, @GANWANSHUI 
thank you for releasing this code.
can i use this work for the single view dataset? i noticed this repo use three views from three cameras.

**Comment by GANWANSHUI** [comment]
Hi,

For the single-view dataset, you need the ego pose to provide the scale information. You may refer to this [work](https://github.com/astra-vision/SceneRF).
