### ISSUE TITLE
Semantic Labels link is dead, new one is available

### ISSUE THREAD

**Issue by seamie6** [GANWANSHUI/GaussianOcc#27]
Your link to the 2D semantic labels in the dataset preparation section is dead. The new link is provided in OccNerf in this issue: https://github.com/LinShan-Bin/OccNeRF/issues/27

Link to labels:
https://cloud.tsinghua.edu.cn/d/564c9ac19b5f4b54a774/

Could you update the link in your repo for others?

**Comment by GANWANSHUI** [comment]
Updated, thanks a lot!
