### ISSUE TITLE
GPU Required for Training

### ISSUE THREAD

**Issue by ShenZheng2000** [GANWANSHUI/GaussianOcc#4]
Hi, how many GPUs and hours are needed to train the model? I have four RTX 4090s and am unsure if that’s enough to reproduce the results

**Comment by GANWANSHUI** [comment]
Hi, 24GB is not enough for this work. We train the model with 8 * A 100 (40 GB) consuming around 12 hours with resnet 50 and around 15 hours with resnet 101.  You may explore some lighter networks such as the [flashocc](https://github.com/Yzichen/FlashOCC), and [Gaussianformer](https://github.com/huang-yh/GaussianFormer) as your backbone.
