### ISSUE TITLE
Custom Single View Dataset

### ISSUE THREAD

**Issue by bob020416** [GANWANSHUI/GaussianOcc#5]
Hi, I want to ask if it's possible to give a customsingle view(like only front driving recorder) for inference?
And  doing front view reconstruction?

Cause it seems multiple view information is required 

Thanks for the response and good work

**Comment by GANWANSHUI** [comment]
This work is for the surrounding view setting, so only the front view requires some modification and retrain the network. You may see [selfocc](https://github.com/huang-yh/SelfOcc) about the SemanticKITTI dataset in the setting of front view only.
