### ISSUE TITLE
Can create novel view synthesis with this model ? 

### ISSUE THREAD

**Issue by RyanPham19092002** [GANWANSHUI/GaussianOcc#8]
Hi, thanks for your great work !
I want to ask can your model create novel view synthesis in nuscene dataset ? If yes, how can I change the target pose to render novel view instead of 6 input views ?
Thank you

**Comment by GANWANSHUI** [comment]
Hi, It can not do the novel view synthesis task for the current model.

**Comment by RyanPham19092002** [comment]
Thanks for your reply.

Vào Th 4, 28 thg 8, 2024 vào lúc 21:00 GANWANSHUI <
***@***.***> đã viết:
