### ISSUE TITLE
conda install fails

### ISSUE THREAD

**Issue by ShenZheng2000** [GANWANSHUI/GaussianOcc#9]
Conda gets stuck on my machine, so I tried using pip install instead. Do you think the slight difference in CUDA will affect model performance?

```
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by GANWANSHUI** [comment]
I did not try other version but I guess it does not matter too much.
